# Site settings

#google_analytics: UA-NNNNNNNN-N

domain: verifier-alliance.github.io
url: https://verifieralliance.org

header_pages:
- index.md
- who.md
- how.md

footer: '<a href="https://github.com/verifieralliance">github</a> | <a href="https://twitter.com/verifalliance">X (twitter)</a> | <a href="https://t.me/verifieralliance">telegram</a>'

style: dark
listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-console

svg:
  optimize: true
